// Router Constants
export const ROUTER_CONSTANTS = {
  PACKET_QUEUE_MAX_SIZE: 4096,
  PROCESSING_SPEED: 1024,
  IP_COL_INDEX: 0,
  MASK_COL_INDEX: 1,
  INTERFACE_COL_INDEX: 2,
  REGENERATE_COL_INDEX: 3,
  TABLE_FIELDS_PER_ROW: 3,
} as const;
